{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPOqV5xbv1cBEgQy12sgqTG"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["!service mysql status"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1709231194295,"user_tz":360,"elapsed":141,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}},"outputId":"d1fc8680-e9b0-42d2-d6f5-2c9782d99c5e","id":"ZEHNdHJNHqPn"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["mysql: unrecognized service\n"]}]},{"cell_type":"code","source":["!service mysql status"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1709231194295,"user_tz":360,"elapsed":141,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}},"outputId":"d1fc8680-e9b0-42d2-d6f5-2c9782d99c5e","id":"859-TvaJHrRa"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["mysql: unrecognized service\n"]}]},{"cell_type":"markdown","source":["# Instalaciones e importaciones"],"metadata":{"id":"mGXxi2qTF5Gq"}},{"cell_type":"code","source":["# Instalación de MySQL Connector Python y Pandas\n","!pip install mysql-connector-python\n","!pip install pandas"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"nCI_y1CCGNCU","executionInfo":{"status":"ok","timestamp":1709231181833,"user_tz":360,"elapsed":13518,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}},"outputId":"51b4e2f2-ba5d-4e0f-fe61-e45be59c7134"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (8.3.0)\n","Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)\n","Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\n"]}]},{"cell_type":"code","source":["# Importamos Pandas\n","import mysql.connector\n","import pandas as pd"],"metadata":{"id":"RhFJG8gDBish","executionInfo":{"status":"ok","timestamp":1709231187773,"user_tz":360,"elapsed":155,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}}},"execution_count":8,"outputs":[]},{"cell_type":"markdown","source":["Prueba importando desde un csv"],"metadata":{"id":"id98X3ulF85o"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"vdU61N7yBVlD"},"outputs":[],"source":["# URL del archivo CSV en GitHub\n","url = 'https://raw.githubusercontent.com/liazamudio/datasets/main/titanic-dataset.csv'\n","\n","# Leer el archivo CSV desde la URL\n","df_titanic = pd.read_csv(url)\n","\n","# Imprimir las primeras filas del DataFrame para verificar\n","df_titanic.head()"]},{"cell_type":"markdown","source":["# Bases de datos"],"metadata":{"id":"X45ZsLZBGC5_"}},{"cell_type":"code","source":["!service mysql status"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"B4PEw9sBHGkD","executionInfo":{"status":"ok","timestamp":1709231194295,"user_tz":360,"elapsed":141,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}},"outputId":"d1fc8680-e9b0-42d2-d6f5-2c9782d99c5e"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["mysql: unrecognized service\n"]}]},{"cell_type":"code","source":["!service mysql start"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"vcjVA0zqHO-J","executionInfo":{"status":"ok","timestamp":1709231116748,"user_tz":360,"elapsed":130,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}},"outputId":"4ea71219-0dc8-4932-8a0c-360a6ff69604"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["mysql: unrecognized service\n"]}]},{"cell_type":"code","source":["# Conexión a la base de datos de MySQL\n","cnx = mysql.connector.connect(\n","   host=\"localhost\",\n","   port=3306,\n","   user=\"root\",\n","   password='2023*DaSci',\n","   database='titanic-passengers'\n",")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":408},"id":"znWRKk8wGFiM","executionInfo":{"status":"error","timestamp":1709230927742,"user_tz":360,"elapsed":175,"user":{"displayName":"Alexandro Ivan Zamudio Romero","userId":"04641586509125630138"}},"outputId":"987b90d9-c3af-45c2-d853-27d926959f0d"},"execution_count":3,"outputs":[{"output_type":"error","ename":"DatabaseError","evalue":"2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMySQLInterfaceError\u001b[0m                       Traceback (most recent call last)","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py\u001b[0m in \u001b[0;36m_open_connection\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    322\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 323\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_cmysql\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mcnx_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    324\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_cmysql\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconverter_str_fallback\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_converter_str_fallback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mMySQLInterfaceError\u001b[0m: Can't connect to MySQL server on 'localhost:3306' (99)","\nThe above exception was the direct cause of the following exception:\n","\u001b[0;31mDatabaseError\u001b[0m                             Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-7948143d222a>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Conexión a la base de datos de MySQL\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m cnx = mysql.connector.connect(\n\u001b[0m\u001b[1;32m      3\u001b[0m    \u001b[0mhost\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"localhost\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m    \u001b[0mport\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3306\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m    \u001b[0muser\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"root\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    320\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    321\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mCMySQLConnection\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0muse_pure\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 322\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mCMySQLConnection\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    323\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mMySQLConnection\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    324\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m    138\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    139\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 140\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    141\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    142\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m   1361\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1362\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdisconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1363\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_open_connection\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1364\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1365\u001b[0m         charset, collation = (\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py\u001b[0m in \u001b[0;36m_open_connection\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    326\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconverter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstr_fallback\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_converter_str_fallback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    327\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mMySQLInterfaceError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0merr\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 328\u001b[0;31m             raise get_mysql_exception(\n\u001b[0m\u001b[1;32m    329\u001b[0m                 \u001b[0mmsg\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0merr\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merrno\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0merr\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merrno\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msqlstate\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0merr\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msqlstate\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    330\u001b[0m             ) from err\n","\u001b[0;31mDatabaseError\u001b[0m: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)"]}]}]}